version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/mysql:latest
        environment:
          MYSQL_DATABASE: resource_management_test
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user_test
          MYSQL_PASSWORD: password
    working_directory: /go/src/github.com/thinhlvv/resource-management
    steps:
      - checkout # checkout working_directory
      - run:
          name: set up environment
          command: |
            cp .env.sample .env
      - run:
          name: install dependencies
          command: |
            GO111MODULE=off go get github.com/mattn/goveralls
            make install 
      - run:
          name: run migrations
          command: |
            make migrate-dbtest
      - run:
          name: run test
          command: |
            make test
            # $GOPATH/bin/goveralls -coverprofile=/go/src/github.com/thinhlvv/resource-management/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
  
workflows:
  resource-management:
    jobs:
      - test:
        filters:
          branches:
            only: master
